name: Dart Tarantool Storage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Native configure
        run: cd static-build && cmake -DCMAKE_TARANTOOL_ARGS="-DCMAKE_BUILD_TYPE=RelWithDebInfo;-DENABLE_WERROR=ON" .

      - name: Native build
        run: cd static-build && make -j 

      - name: Dart dependencies
        run: cd binding/dart && dart pub get

      - name: Run tests
        run: cd binding/dart && dart compile exe test/test.dart && ./test/test.exe && ./test/test-replication.sh